<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>resl</string>
    <key>scopeName</key>
    <string>source.resl</string>
    <key>fileTypes</key>
    <array>
      <string>resl</string>
    </array>
    <key>uuid</key>
    <string>5899f948-bdc0-4cb9-b282-50efe7c6d15d</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#component</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.resl</string>
            <key>begin</key>
            <string>\-\-</string>
            <key>end</key>
            <string>$</string>
          </dict>
        </array>
      </dict>
      <key>package</key>
      <dict>
        <key>begin</key>
        <string>(package)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>import</key>
      <dict>
        <key>begin</key>
        <string>(import)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>internal</key>
      <dict>
        <key>match</key>
        <string>(int|double|string|bool)</string>
        <key>name</key>
        <string>storage.type.resl</string>
      </dict>
      <key>word</key>
      <dict>
        <key>match</key>
        <string>([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>name</key>
        <string>entity.name.class.resl</string>
      </dict>
      <key>normal_field</key>
      <dict>
        <key>begin</key>
        <string>((int|double|string|bool)|([A-Za-z][A-Za-z0-9_\.]*))\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>map_field</key>
      <dict>
        <key>begin</key>
        <string>(map)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>list_field</key>
      <dict>
        <key>begin</key>
        <string>(list)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>event_field</key>
      <dict>
        <key>begin</key>
        <string>(event)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(\s*([A-Za-z][A-Za-z0-9_\.]*)?\s*\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>command_field</key>
      <dict>
        <key>begin</key>
        <string>(command)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(([A-Za-z][A-Za-z0-9_\.]*)?\)\s*([A-Za-z][A-Za-z0-9_\.]*)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>type</key>
      <dict>
        <key>begin</key>
        <string>(type)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.struct.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>component</key>
      <dict>
        <key>begin</key>
        <string>(component)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*(\d+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#event_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#command_field</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>resl</string>
    <key>scopeName</key>
    <string>source.resl</string>
    <key>fileTypes</key>
    <array>
      <string>resl</string>
    </array>
    <key>uuid</key>
    <string>5899f948-bdc0-4cb9-b282-50efe7c6d15d</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#component</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.resl</string>
            <key>begin</key>
            <string>\-\-</string>
            <key>end</key>
            <string>$</string>
          </dict>
        </array>
      </dict>
      <key>package</key>
      <dict>
        <key>begin</key>
        <string>(package)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>import</key>
      <dict>
        <key>begin</key>
        <string>(import)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>internal</key>
      <dict>
        <key>match</key>
        <string>(int|double|string|bool)</string>
        <key>name</key>
        <string>storage.type.resl</string>
      </dict>
      <key>word</key>
      <dict>
        <key>match</key>
        <string>([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>name</key>
        <string>entity.name.class.resl</string>
      </dict>
      <key>normal_field</key>
      <dict>
        <key>begin</key>
        <string>((int|double|string|bool)|([A-Za-z][A-Za-z0-9_\.]*))\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>map_field</key>
      <dict>
        <key>begin</key>
        <string>(map)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>list_field</key>
      <dict>
        <key>begin</key>
        <string>(list)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>event_field</key>
      <dict>
        <key>begin</key>
        <string>(event)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(\s*([A-Za-z][A-Za-z0-9_\.]*)?\s*\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>command_field</key>
      <dict>
        <key>begin</key>
        <string>(coand)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(([A-Za-z][A-Za-z0-9_\.]*)\)\s*([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>type</key>
      <dict>
        <key>begin</key>
        <string>(type)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.struct.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>component</key>
      <dict>
        <key>begin</key>
        <string>(component)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*(\d+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#event_field</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>