<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>resl</string>
    <key>scopeName</key>
    <string>source.resl</string>
    <key>fileTypes</key>
    <array>
      <string>resl</string>
    </array>
    <key>uuid</key>
    <string>5899f948-bdc0-4cb9-b282-50efe7c6d15d</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#component</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#extend</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#enum</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#service</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.resl</string>
            <key>begin</key>
            <string>\-\-</string>
            <key>end</key>
            <string>$</string>
          </dict>
        </array>
      </dict>
      <key>package</key>
      <dict>
        <key>begin</key>
        <string>(package)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>import</key>
      <dict>
        <key>begin</key>
        <string>(import)\s+([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>internal</key>
      <dict>
        <key>match</key>
        <string>(int|double|string|bool)</string>
        <key>name</key>
        <string>storage.type.resl</string>
      </dict>
      <key>callable</key>
      <dict>
        <key>match</key>
        <string>(callable)\s*=\s*(SelfClient|AllClient|NoClient|All)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.enum.resl</string>
          </dict>
        </dict>
      </dict>
      <key>default</key>
      <dict>
        <key>match</key>
        <string>(default)\s*=\s*((\d+)|(true|false)|(nil)|(\"[^\"]*\"))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.resl</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.null.resl</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.resl</string>
          </dict>
        </dict>
      </dict>
      <key>replicated</key>
      <dict>
        <key>match</key>
        <string>(replicated)\s*=\s*(SelfClient|None|NoClient|All)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.enum.resl</string>
          </dict>
        </dict>
      </dict>
      <key>persistent</key>
      <dict>
        <key>match</key>
        <string>(persistent)\s*=\s*(true|false)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.resl</string>
          </dict>
        </dict>
      </dict>
      <key>word</key>
      <dict>
        <key>match</key>
        <string>([A-Za-z][A-Za-z0-9_\.]*)</string>
        <key>name</key>
        <string>entity.name.class.resl</string>
      </dict>
      <key>attribute_field</key>
      <dict>
        <key>begin</key>
        <string>\[\s*</string>
        <key>end</key>
        <string>\s*\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#callable</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#default</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#replicated</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#persistent</string>
          </dict>
        </array>
      </dict>
      <key>normal_field</key>
      <dict>
        <key>match</key>
        <string>((int|double|string|bool)|([A-Za-z][A-Za-z0-9_\.]*))\s+([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>map_field</key>
      <dict>
        <key>begin</key>
        <string>(map)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>list_field</key>
      <dict>
        <key>begin</key>
        <string>(list)\s*\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;\s*([A-Za-z][A-Za-z0-9_\.]*)\s*=\s*(\d+)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#internal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#word</string>
          </dict>
        </array>
      </dict>
      <key>event_field</key>
      <dict>
        <key>match</key>
        <string>(event)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(\s*([A-Za-z][A-Za-z0-9_\.]*)?\s*\)\s*=\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.function.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>command_field</key>
      <dict>
        <key>match</key>
        <string>(command)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\(([A-Za-z][A-Za-z0-9_\.]*)?\)\s*([A-Za-z][A-Za-z0-9_\.]*)?\s*=\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.function.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.resl</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>enum_field</key>
      <dict>
        <key>match</key>
        <string>([A-Za-z][A-Za-z0-9_.]*)\s*=\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>option_field</key>
      <dict>
        <key>match</key>
        <string>(option)\s+(persistent|replicated)\s*=\s*(true|false)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.resl</string>
          </dict>
        </dict>
      </dict>
      <key>service_field</key>
      <dict>
        <key>match</key>
        <string>(rpc)\s+([A-Za-z][A-Za-z0-9_.]*)\s*\(\s*([A-Za-z][A-Za-z0-9_.]*)\s*\)\s*([A-Za-z][A-Za-z0-9_.]*)?\s*=\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.word</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.function.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.resl</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.resl</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
      </dict>
      <key>type</key>
      <dict>
        <key>begin</key>
        <string>(type)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.struct.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.struct.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
        </array>
      </dict>
      <key>extend</key>
      <dict>
        <key>begin</key>
        <string>(extend)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#event_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#command_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#option_field</string>
          </dict>
        </array>
      </dict>
      <key>component</key>
      <dict>
        <key>begin</key>
        <string>(component)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*(\d+)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.class.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.resl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#map_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#event_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#command_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#normal_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attribute_field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#option_field</string>
          </dict>
        </array>
      </dict>
      <key>enum</key>
      <dict>
        <key>begin</key>
        <string>(enum)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.enum.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.enum.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum_field</string>
          </dict>
        </array>
      </dict>
      <key>service</key>
      <dict>
        <key>begin</key>
        <string>(service)\s+([A-Za-z][A-Za-z0-9_\.]*)\s*\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.service.resl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.service.resl</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#service_field</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>